=== pushpak4/Programming---JAVA-or-Python/Theater.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Theater (Details+)>
<!ELEMENT Details (Movie,Generes)>
<!ELEMENT Movie (#PCDATA)>
<!ELEMENT Generes (#PCDATA)>

=== pushpak4/Programming---JAVA-or-Python/theater.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Theater SYSTEM "Theater.dtd">
<Theater>
   <Details>
      <Movie>Jhon Wick</Movie>
      <Generes>Action</Generes>
   </Details>
   <Details>
      <Movie>Shazam</Movie>
      <Generes>Action</Generes>
   </Details>
   <Details>
      <Movie>Scream</Movie>
      <Generes>Horror</Generes>
   </Details>
</Theater>
